

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Columbia PIT" # the name of your site, e.g. ACME Corp.
tagline: "Public Interest Technology"
email: "chilton@cs.columbia.edu"
description: >- # this means to ignore newlines until "baseurl:"
author: Lydia Chilton
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
collections_dir: all_collections
collections:  
  people:
    output: true
    permalink: /:collection/:path/
    # sort_by: last_name
  fall20_projects:
    output: true
